In [1]:
import numpy as np

# Data Types & Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[20,21,22],
                [23,24,25],
                [26,27,28]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

# Creating Arrays

In [5]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [6]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array = np.random.randint(0, 10, (3, 4))
random_array

array([[7, 4, 5, 2],
       [6, 2, 5, 3],
       [9, 7, 8, 2]])

In [10]:
random_array_2 = np.random.random((3,4))
random_array_2

array([[0.95036512, 0.94293833, 0.25540641, 0.9478001 ],
       [0.43757193, 0.70282262, 0.80392599, 0.71481816],
       [0.37043632, 0.33493689, 0.52213267, 0.85624715]])

In [11]:
random_array_3 = np.random.rand(3,4)
random_array_3

array([[0.05772389, 0.00169548, 0.49605249, 0.52666546],
       [0.25581724, 0.07959184, 0.08257459, 0.42819901],
       [0.106177  , 0.59277282, 0.38709049, 0.50160375]])

In [12]:
random_array_sum = random_array + random_array_2
random_array_sum

array([[7.95036512, 4.94293833, 5.25540641, 2.9478001 ],
       [6.43757193, 2.70282262, 5.80392599, 3.71481816],
       [9.37043632, 7.33493689, 8.52213267, 2.85624715]])

## Random Arrays can be used to fill up a DataFrame

Here below is an example of using an one-dimensional array to creat a column in a dataframe

In [13]:
prices = np.random.randint(50, 300, 10)
prices

array([ 66, 239,  90, 128, 290, 201,  51, 270, 121, 187])

In [14]:
df = pd.DataFrame({"Price":prices})
df

Price
0     66
1    239
2     90
3    128
4    290
5    201
6     51
7    270
8    121
9    187

Here below is an example of using a two-dimensional array to creat a dataframe with multi-columns

In [15]:
df = pd.DataFrame(random_array_sum)
df

0         1         2         3
0  7.950365  4.942938  5.255406  2.947800
1  6.437572  2.702823  5.803926  3.714818
2  9.370436  7.334937  8.522133  2.856247

# Random Seeds

Random numbers stays the same if we use the seed function.

They still being random, they just don't change anymore.

In [36]:
np.random.seed(0)

random_array_4 = np.random.randint(0, 10, (5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [50]:
np.random.seed(7)

random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])